name: Phase 1 - MLOps Pipeline

on:

  push:
    branches: [main]

jobs:

  # 🔹 CI JOB (PR validation)
  ci:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Basic Import Check
        run: python -c "import src.train; print('Import OK')"

      - name: Run Training (CI Mode)
        run: |
          export ENV=ci
          python src/train.py


  # 🔹 CD JOB (Main branch only)
  cd:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train + Register Model
        run: |
          export ENV=ci
          python src/train.py

      - name: Build Docker Image
        run: docker build -t sentiment-app-v1 .